name: catchspike
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_dotenv: ^5.0.2

  cupertino_icons: ^1.0.8
  kakao_flutter_sdk: ^1.9.6

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansLight.otf
          weight: 300
        - asset: assets/fonts/GmarketSansMedium.otf
          weight: 500
        - asset: assets/fonts/GmarketSansBold.otf
          weight: 700
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700